 image: atlassian/default-image:latest
 pipelines:
   default:
     - step:
        name: Deploy to BMM API
        deployment: production
        script:
            - ssh centos@52.79.251.52 'bash -s' < ./build/deploy.sh
            - echo "Deploy step finished"