version: '3.7'

services:
    dev:
        build:
            context: .
            dockerfile: Dockerfile.dev
        container_name: dev-api
        working_dir: /usr/src/app
        env_file:
            - .env
        environment:
            - NODE_ENV=development
        restart: unless-stopped
        networks:
            - app-network
        volumes:
            - .:/usr/src/app
            - node_modules:/usr/src/app/node_modules
        ports:
            - '8989:8989'
volumes:
    node_modules:
networks:
    app-network:
        driver: bridge
