branch-defaults:
    test:
        environment: $BITBUCKET_DEPLOYMENT_ENVIRONMENT
global:
    application_name: bmm
    branch: $BITBUCKET_DEPLOYMENT_ENVIRONMENT
    default_ec2_keyname: event
    default_platform: Docker 18.09.9-ce
    default_region: ap-northeast-2
    include_git_submodules: true
    instance_profile: null
    platform_name: null
    platform_version: null
    profile: eb-cli
    repository: null
    sc: git
    workspace_type: Application
